name: Build caddy-crowdsec

on:
  pull_request:
    paths: ['.github/workflows/build-caddy-crowdsec.yml', 'caddy-crowdsec/**']
  push:
    branches: [main]
    paths: ['.github/workflows/build-caddy-crowdsec.yml', 'caddy-crowdsec/**']
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      # renovate: datasource=docker depName=caddy
      CADDY_VERSION: 2.11.4
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7

      - uses: docker/setup-qemu-action@96fe6ef7f33517b61c61be40b68a1882f3264fb8 # v4

      - uses: docker/setup-buildx-action@37fe631027851001ddb9b187196cc803df7f5f0e # v4

      - uses: docker/login-action@dbcb813823bdd20940b903addbd779551569679f # v4
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push caddy-crowdsec
        uses: docker/build-push-action@53b7df96c91f9c12dcc8a07bcb9ccacbed38856a # v7
        with:
          context: caddy-crowdsec
          platforms: linux/amd64
          push: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
          tags: |
            ghcr.io/bl4ko/caddy-crowdsec:latest
            ghcr.io/bl4ko/caddy-crowdsec:${{ env.CADDY_VERSION }}
          cache-from: type=gha,scope=caddy-crowdsec
          cache-to: type=gha,scope=caddy-crowdsec,mode=max
