name: CI

on:
  pull_request:
  push:
    branches: [main]

permissions:
  contents: read

jobs:
  scan:
    uses: bl4ko/shared-actions/.github/workflows/gitleaks.yml@a18e42a53083438150a76e57bc3a4e32698cd81f # main
