name: CI

on:
  pull_request:
  push:
    branches: [main]

permissions:
  contents: read

jobs:
  scan:
    uses: bl4ko/shared-actions/.github/workflows/gitleaks.yml@c407a22baf9b6b7bff19ad42b0d4e754d16a6adc # main
