name: CI

on:
  pull_request:
  push:
    branches: [main]

permissions:
  contents: read

jobs:
  scan:
    uses: bl4ko/shared-actions/.github/workflows/gitleaks.yml@96c04bc028d3529c4c2e2a1d023eef989d185d02 # main
